# Keyword Rules Configuration
# Priority levels: 1 (low) to 5 (high)

# High priority India-specific keywords
india_topics:
  priority: 3
  match_type: "partial"  # exact, partial, regex
  match_location: "both"  # title, body, both
  response_template: "india_specific"
  keywords:
    # Places
    - "india"
    - "indian"
    - "delhi"
    - "mumbai"
    - "bangalore"
    - "bengaluru"
    - "chennai"
    - "kolkata"
    - "hyderabad"
    - "pune"
    - "ahmedabad"
    - "jaipur"
    - "lucknow"
    - "kanpur"
    - "nagpur"
    - "indore"
    - "bhopal"
    - "visakhapatnam"
    - "kerala"
    - "goa"
    - "rajasthan"
    - "maharashtra"
    - "karnataka"
    - "tamil nadu"
    - "west bengal"
    - "uttar pradesh"
    
    # Politics and governance
    - "modi"
    - "bjp"
    - "congress"
    - "aap"
    - "election"
    - "parliament"
    - "lok sabha"
    - "rajya sabha"
    - "supreme court"
    
    # Culture and festivals
    - "diwali"
    - "holi"
    - "dussehra"
    - "navratri"
    - "eid"
    - "christmas"
    - "ganesh chaturthi"
    - "karva chauth"
    - "bollywood"
    - "cricket"
    - "ipl"
    - "hindi"
    - "bollywood"
    - "classical music"
    - "bharatanatyam"
    - "yoga"
    
    # Economy and business
    - "rupee"
    - "nse"
    - "bse"
    - "sensex"
    - "nifty"
    - "startup"
    - "unicorn"
    - "fintech"
    - "upi"
    - "paytm"
    - "flipkart"
    - "amazon india"
    - "tata"
    - "reliance"
    - "infosys"
    - "wipro"
    - "tcs"
    
    # Technology
    - "silicon valley of india"
    - "it sector"
    - "software engineer"
    - "tech hub"
    - "digital india"
    - "aadhaar"
    - "jan dhan"
    
    # Food
    - "curry"
    - "biryani"
    - "samosa"
    - "chai"
    - "masala"
    - "naan"
    - "roti"
    - "dal"
    - "paneer"
    - "tandoor"
    - "spicy food"
    - "indian cuisine"

# Medium priority advice and help keywords
advice_help:
  priority: 2
  match_type: "partial"
  match_location: "both"
  response_template: "helpful_advice"
  keywords:
    # General help requests
    - "advice"
    - "help"
    - "suggestion"
    - "recommend"
    - "opinion"
    - "what should i"
    - "how do i"
    - "need help"
    - "confused"
    - "stuck"
    - "guidance"
    - "tips"
    
    # Career and work
    - "career"
    - "job"
    - "interview"
    - "salary"
    - "work"
    - "workplace"
    - "boss"
    - "colleague"
    - "promotion"
    - "resignation"
    - "job search"
    - "resume"
    - "cv"
    - "linkedin"
    
    # Education
    - "college"
    - "university"
    - "degree"
    - "course"
    - "study"
    - "exam"
    - "student"
    - "scholarship"
    - "education"
    - "learning"
    
    # Relationships and personal
    - "relationship"
    - "dating"
    - "marriage"
    - "family"
    - "friends"
    - "parents"
    - "breakup"
    - "love"
    - "wedding"
    - "social skills"
    - "confidence"

# Medium priority technology keywords
technology:
  priority: 2
  match_type: "partial"
  match_location: "both"
  response_template: "tech_discussion"
  keywords:
    # Programming
    - "programming"
    - "coding"
    - "developer"
    - "software"
    - "python"
    - "javascript"
    - "java"
    - "c++"
    - "react"
    - "nodejs"
    - "django"
    - "flask"
    - "html"
    - "css"
    - "sql"
    - "database"
    - "api"
    - "github"
    - "git"
    
    # AI and Data
    - "ai"
    - "artificial intelligence"
    - "machine learning"
    - "data science"
    - "deep learning"
    - "neural network"
    - "chatgpt"
    - "llm"
    - "algorithm"
    - "data analysis"
    - "statistics"
    
    # General tech
    - "startup"
    - "tech"
    - "software engineer"
    - "web development"
    - "mobile app"
    - "android"
    - "ios"
    - "cloud"
    - "aws"
    - "azure"
    - "docker"
    - "kubernetes"

# Low priority general discussion keywords
general_discussion:
  priority: 1
  match_type: "partial"
  match_location: "both"
  response_template: "general"
  keywords:
    - "interesting"
    - "thoughts"
    - "discussion"
    - "debate"
    - "explain"
    - "understand"
    - "curious"
    - "question"
    - "why"
    - "how"
    - "what"

# Blacklist keywords (posts containing these will be ignored)
blacklist:
  keywords:
    - "suicide"
    - "self harm"
    - "kill myself"
    - "depression"
    - "mental health crisis"
    - "drugs"
    - "illegal"
    - "porn"
    - "nsfw"
    - "hate"
    - "violence"
    - "terrorist"
    - "bomb"
    - "weapon"
    - "murder"
    - "rape"
    - "abuse"
    - "scam"
    - "fraud"
    - "bitcoin"
    - "cryptocurrency"
    - "investment scheme"
    - "get rich quick"